name: macOS Release

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Build
        run: |
          pip install -r requirements.txt
          pyinstaller --noconsole -F ./main.py --icon icon.png -n gofile-launcher-mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/gofile-launcher-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}